/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace stock {
    export interface StockService {
        getStockUpdates(
            data: Observable<Empty>,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<StockList>;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {
    }
    export interface StockResponse {
        symbol?: string;
        price?: number;
    }
    export interface StockList {
        stock?: stock.StockResponse[];
    }
}

