/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace message {
    export interface MessageService {
        findOne(
            data: MessageById,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Message>;
        findMany(
            data: Observable<MessageById>,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Message>;
    }
    export interface MessageById {
        id?: number;
    }
    export interface Message {
        id?: number;
        name?: string;
    }
}

