/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace chat {
    export interface ChatService {
        connect(
            data: ChatConnection,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Empty>;
        sendMessage(
            data: ChatMessage,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Empty>;
        onMessageUpdated(
            data: Empty,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ChatMessage>;
    }
    export interface ChatConnection {
        userId?: string;
        username?: string;
    }
    export interface ChatMessage {
        userId?: string;
        username?: string;
        content?: string;
        timestamp?: number;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {
    }
}

