/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace stream {
    export interface StreamService {
        findOne(
            data: StreamRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<StreamResponse>;
        bidiStrings(
            data: Observable<StreamRequest>,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<StreamResponse>;
    }
    export interface StreamRequest {
        greetings?: string;
    }
    export interface StreamResponse {
        message?: string;
    }
}

